server:
  port: 8081
  
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'SUA SENHA'
    username: 'SEU USUARIO'
    url: jdbc:mysql://localhost:3306/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
